"use client";
import {useEffect,useState} from "react";
import {BarChart3,SlidersHorizontal,Gift,Bell,Save,LockKeyhole,Check,RefreshCw,X,LoaderCircle} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Slider} from "@/components/ui/slider";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {toast} from "sonner";
import {Config,StageState,Round,percent,taipeiDay,prizeColor} from "@/lib/model";
import {api,ApiError} from "@/lib/client";

export default function Admin({open,state,activityId,authStamp=0,onClose,onSaved,onSound,onLock,onReauth}:{open:boolean;state:StageState;activityId:string;authStamp?:number;onClose:()=>void;onSaved:(s:StageState)=>void;onSound:(volume:number)=>void;onLock:()=>void;onReauth:()=>void}){
 const [draft,setDraft]=useState<Config>(state.config),[baseline,setBaseline]=useState(JSON.stringify(state.config)),[revision,setRevision]=useState(state.revision),[tab,setTab]=useState("prizes"),[prizeChoice,setPrizeChoice]=useState(state.config.prizes[0].id),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState<"discard"|"pool"|null>(null),[records,setRecords]=useState<Round[]>([]),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState(""),[day,setDay]=useState(taipeiDay()),[pins,setPins]=useState({currentPin:"",newPin:"",confirmPin:""});
 const dirty=JSON.stringify(draft)!==baseline,total=draft.prizes.reduce((s,p)=>s+Math.round((p.weight||0)*100),0)/100,totalStock=state.config.prizes.reduce((sum,p)=>sum+(state.stock[p.id]??0),0),planned=draft.prizes.reduce((a,p)=>a+p.quantity,0),known=draft.prizes.every(p=>p.cost!==null),avg=draft.prizes.reduce((s,p)=>s+(p.cost||0)*(draft.mode==="pool"?(planned?p.quantity/planned:0):p.weight/100),0);
 useEffect(()=>{if(open){setDraft(structuredClone(state.config));setPrizeChoice(current=>state.config.prizes.some(p=>p.id===current)?current:state.config.prizes[0].id);setBaseline(JSON.stringify(state.config));setRevision(state.revision);setError("");setPins({currentPin:"",newPin:"",confirmPin:""});}},[open]);
 useEffect(()=>{setError("");},[authStamp]);
 useEffect(()=>{if(!open||tab!=="history")return;let alive=true;setHistoryBusy(true);setHistoryError("");api<{rounds:Round[]}>(`history?activity=${encodeURIComponent(activityId)}${day?"&day="+day:""}`).then(r=>{if(alive)setRecords(r.rounds);}).catch(e=>{if(alive){setHistoryError(e.message);if(e instanceof ApiError&&e.status===401)setError(e.message);}}).finally(()=>{if(alive)setHistoryBusy(false);});return()=>{alive=false;};},[open,tab,day,state.stats.completed,authStamp,activityId]);
 function close(){if(busy)return;if(dirty)setConfirm("discard");else onClose();}
 function accept(s:StageState){onSaved(s);setDraft(structuredClone(s.config));setPrizeChoice(current=>s.config.prizes.some(p=>p.id===current)?current:s.config.prizes[0].id);setBaseline(JSON.stringify(s.config));setRevision(s.revision);}
 function failure(e:unknown){setError((e as Error).message);if(e instanceof ApiError&&e.status===401)toast.error("管理驗證已過期，請按「重新驗證」。");}
 async function save(){setBusy(true);setError("");try{accept(await api<StageState>("settings",{config:draft,revision,activityId}));toast.success("活動設定已儲存");}catch(e){failure(e);}finally{setBusy(false);}}
 async function pool(){setConfirm(null);setBusy(true);setError("");try{accept(await api<StageState>("pool",{revision,activityId}));toast.success("新獎池已啟用，原有紀錄保留");}catch(e){failure(e);}finally{setBusy(false);}}
 async function changePin(){setBusy(true);setError("");try{await api("pin",pins);setPins({currentPin:"",newPin:"",confirmPin:""});toast.success("管理 PIN 已更新，其他裝置需重新驗證");}catch(e){failure(e);}finally{setBusy(false);}}
 const updatePrize=(i:number,key:string,value:unknown)=>setDraft(d=>({...d,prizes:d.prizes.map((p,j)=>i===j?{...p,[key]:value}:p)}));
 return <><Dialog open={open} onOpenChange={v=>{if(!v)close();}}><DialogContent className="admin-dialog" showCloseButton={false} onOpenAutoFocus={e=>e.preventDefault()}><header className="admin-header"><div><span className="admin-eyebrow">{state.config.eventName}</span><DialogTitle>管理設定</DialogTitle><DialogDescription>設定獎品、機率與活動內容。</DialogDescription></div><Button variant="ghost" className="close-control" onClick={close} aria-label="關閉管理設定"><X size={22}/></Button></header><Tabs value={tab} onValueChange={setTab} className="admin-tabs"><TabsList className="admin-tab-list"><TabsTrigger value="prizes"><Gift/>獎項與機率</TabsTrigger>{draft.mode==="pool"?<TabsTrigger value="pool"><RefreshCw/>獎池管理</TabsTrigger>:null}<TabsTrigger value="event"><SlidersHorizontal/>舞台設定</TabsTrigger><TabsTrigger value="history"><BarChart3/>活動紀錄</TabsTrigger></TabsList><div className="admin-scroll">
 <TabsContent value="prizes"><div className="admin-section-head"><div><h3>選擇抽獎方式</h3><p>轉盤等分呈現，依設定機率或獎池份數抽出。</p></div><span className={`total-pill ${Math.abs(total-100)>.001?"invalid":""}`}>{total===100?<Check size={16}/>:null}機率合計 {Number(total.toFixed(2))}%</span></div><RadioGroup className="mode-options" value={draft.mode} onValueChange={v=>setDraft(d=>({...d,mode:v as Config["mode"]}))}><label className={draft.mode==="probability"?"selected":""}><RadioGroupItem value="probability"/><span><strong>固定機率</strong><small>每次依設定機率抽出，不限抽獎次數。</small></span></label><label className={draft.mode==="pool"?"selected":""}><RadioGroupItem value="pool"/><span><strong>固定獎池</strong><small>抽出即扣除一份，機率隨剩餘數量變動。</small></span></label></RadioGroup>
 <Tabs className="single-prize-editor" value={prizeChoice} onValueChange={setPrizeChoice}><TabsList className="prize-choice-list" aria-label="選擇要設定的獎品">{draft.prizes.map((p,i)=><TabsTrigger key={p.id} value={p.id}><span>{String(i+1).padStart(2,"0")} {p.shortName||"獎項"}</span><b>{p.weight}%</b></TabsTrigger>)}</TabsList><div className="prize-editor">{draft.prizes.map((p,i)=><TabsContent value={p.id} className="prize-edit-row" key={p.id}><div className="prize-edit-heading"><span style={{background:prizeColor(p.id)}}>{String(i+1).padStart(2,"0")}</span><strong>{p.shortName||"獎項 "+(i+1)}</strong></div><div className="prize-edit-fields"><label className="field full-name"><span>獎項名稱</span><Input aria-label={`獎項 ${i+1} 名稱`} value={p.name} maxLength={40} onChange={e=>updatePrize(i,"name",e.target.value)}/></label><label className="field"><span>轉盤短名</span><Input aria-label={`獎項 ${i+1} 轉盤短名`} value={p.shortName} maxLength={10} onChange={e=>updatePrize(i,"shortName",e.target.value)}/></label><label className="field"><span>機率 %</span><Input type="number" inputMode="decimal" min="0" max="100" step="0.01" aria-label={`獎項 ${i+1} 機率`} value={p.weight} onChange={e=>updatePrize(i,"weight",Number(e.target.value))}/></label>{draft.mode==="pool"?<label className="field"><span>新獎池份數</span><Input type="number" inputMode="numeric" min="0" max="10000" aria-label={`獎項 ${i+1} 獎池份數`} value={p.quantity} onChange={e=>updatePrize(i,"quantity",Number(e.target.value))}/></label>:null}<label className="field"><span>單份成本 NT$</span><Input type="number" inputMode="decimal" min="0" max="1000" placeholder="待確認" aria-label={`獎項 ${i+1} 單份成本`} value={p.cost??""} onChange={e=>updatePrize(i,"cost",e.target.value===""?null:Number(e.target.value))}/></label></div></TabsContent>)}</div></Tabs>
 <div className="cost-summary"><div><span>{draft.mode==="pool"?"新獎池平均單份成本":"單次平均贈品成本"}</span><strong>{known?`NT$ ${Math.round(avg).toLocaleString()}`:"待填寫實際成本"}</strong></div><p>{known?`最高單份 NT$ ${Math.max(...draft.prizes.map(p=>p.cost||0)).toLocaleString()}${draft.mode==="pool"?` · 新獎池總成本 NT$ ${draft.prizes.reduce((a,p)=>a+(p.cost||0)*p.quantity,0).toLocaleString()}`:""}`:"請填寫實際進價。每項成本上限為 NT$1,000；未填齊前，無法確認整體預算。"}</p></div></TabsContent>
 <TabsContent value="pool">{draft.mode==="pool"?<section className="pool-management"><div className="admin-section-head"><div><h3>本場獎池 <span>#{String(state.config.poolNumber).padStart(2,"0")}</span></h3><p>目前還有 <b>{totalStock}</b> 份好禮。新獎池預計準備 {planned} 份。</p></div><Button variant="outline" disabled={busy||dirty||!!state.active||planned===0} onClick={()=>setConfirm("pool")}><RefreshCw/>啟用新獎池</Button></div><div className="stock-grid">{state.config.prizes.map(p=><div key={p.id}><span>{p.shortName}</span><strong>{state.stock[p.id]??0}<small>份</small></strong></div>)}</div><p className="field-help">調整份數後請先儲存，再啟用新獎池。固定數量可控制每項份數與總成本；原有紀錄會保留。</p></section>:null}</TabsContent>
 <TabsContent value="event"><section className="settings-section"><h3>活動與設備</h3><label className="field"><span>設備名稱</span><Input value={draft.deviceName} maxLength={30} onChange={e=>setDraft(d=>({...d,deviceName:e.target.value}))}/></label><label className="field"><span>活動名稱</span><Input value={draft.eventName} maxLength={60} onChange={e=>setDraft(d=>({...d,eventName:e.target.value}))}/></label><label className="field"><span>成交公告文字</span><Input value={draft.announcement} maxLength={60} onChange={e=>setDraft(d=>({...d,announcement:e.target.value}))}/></label><label className="field"><span>抽獎引導文字</span><Input value={draft.inviteText} maxLength={60} onChange={e=>setDraft(d=>({...d,inviteText:e.target.value}))}/></label><div className="range-row"><div><label>成交動畫時間</label><strong>{draft.announcementSeconds} 秒</strong></div><Slider aria-label="成交動畫時間" min={3} max={5} step={1} value={[draft.announcementSeconds]} onValueChange={v=>setDraft(d=>({...d,announcementSeconds:v[0]}))}/><p>公告後自動進入轉盤；轉盤旋轉時間固定約 5.2 秒。</p></div><div className="range-row"><div><label>音效音量</label><strong>{draft.volume}%</strong></div><Slider aria-label="音效音量" min={0} max={100} step={5} value={[draft.volume]} onValueChange={v=>setDraft(d=>({...d,volume:v[0]}))}/><Button variant="outline" onClick={()=>onSound(draft.volume)}><Bell/>試聽成交鈴聲</Button></div></section><section className="settings-section security-section"><h3><LockKeyhole size={19}/>管理 PIN</h3><p className="field-help">PIN 為 4 位數。更新後，其他裝置需要重新驗證。</p><div className="pin-change-fields">{[["currentPin","目前 PIN"],["newPin","新 PIN"],["confirmPin","再次輸入新 PIN"]].map(([key,label])=><label className="field" key={key}><span>{label}</span><Input type="password" inputMode="numeric" maxLength={4} autoComplete="off" value={pins[key as keyof typeof pins]} onChange={e=>setPins(p=>({...p,[key]:e.target.value.replace(/\D/g,"")}))}/></label>)}</div><div className="security-actions"><Button variant="outline" onClick={changePin} disabled={busy||Object.values(pins).some(p=>p.length!==4)}>更新管理 PIN</Button><Button variant="ghost" onClick={onLock} disabled={busy||!!state.active||dirty}><LockKeyhole/>鎖定此裝置</Button></div></section></TabsContent>
 <TabsContent value="history"><div className="admin-section-head"><div><h3>今日活動表現</h3><p>{taipeiDay()} · 台灣時間</p></div><span className="history-badge">正式活動</span></div><div className="stat-grid"><div><span>成交啟動</span><strong>{state.stats.started}<small>次</small></strong></div><div><span>完成抽獎</span><strong>{state.stats.completed}<small>次</small></strong></div><div><span>尚待抽獎</span><strong>{state.stats.started-state.stats.completed}<small>次</small></strong></div></div><div className="draw-counts">{state.config.prizes.map(p=><div key={p.id}><span><i style={{background:prizeColor(p.id)}}/>{p.shortName}</span><strong>{state.stats.byPrize[p.id]||0}<small>份</small></strong></div>)}</div><div className="history-controls"><h3>成交與獎項紀錄</h3><label className="field"><span className="sr-only">篩選紀錄日期</span><Input type="date" aria-label="篩選紀錄日期" value={day} onChange={e=>setDay(e.target.value)}/></label><Button variant="ghost" onClick={()=>setDay("")}>最近紀錄</Button></div><p className="field-help">依成交時間顯示最近 100 筆；中獎結果自動保存。</p>{historyBusy?<p className="empty-history"><LoaderCircle className="animate-spin"/>讀取紀錄中</p>:historyError?<p role="alert" className="form-error">{historyError}</p>:records.length===0?<div className="empty-history"><Gift size={30}/><h4>等待第一個幸運時刻</h4><p>正式成交後，抽獎紀錄會出現在這裡。</p></div>:<Table className="history-table"><TableHeader><TableRow><TableHead>編號 / 時間</TableHead><TableHead>抽中好禮</TableHead><TableHead>狀態</TableHead><TableHead>登記備註</TableHead></TableRow></TableHeader><TableBody>{records.map(r=><TableRow key={r.id}><TableCell><b>#{String(r.sequence).padStart(3,"0")}</b><small>{new Date(r.createdAt).toLocaleString("zh-TW",{timeZone:"Asia/Taipei",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}</small></TableCell><TableCell>{r.outcome?.prize.name||"等待抽獎"}</TableCell><TableCell><span className={`record-status ${r.status}`}>{r.status==="complete"?"已登記":r.status==="drawn"?"待登記":"待抽獎"}</span></TableCell><TableCell className="note-cell">{r.note||"—"}</TableCell></TableRow>)}</TableBody></Table>}</TabsContent>
 </div></Tabs><footer className="admin-bottom"><div><p className="form-error" role="alert">{error}</p>{error.includes("PIN")?<Button variant="link" onClick={onReauth}>重新驗證</Button>:null}<span>{state.active?"目前有成交進行中，回到待機後即可修改。":total!==100?"機率合計必須等於 100%，請調整後再儲存。":dirty?"尚有未儲存的變更":"設定已同步 · 機率合計 100%"}</span></div><Button className="save-button" onClick={save} disabled={busy||!dirty||total!==100||!!state.active}>{busy?<LoaderCircle className="animate-spin"/>:<Save/>}儲存設定</Button></footer></DialogContent></Dialog><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null);}}><AlertDialogContent className="confirm-dialog"><AlertDialogTitle>{confirm==="pool"?"啟用新的固定獎池？":"離開前尚未儲存"}</AlertDialogTitle><AlertDialogDescription>{confirm==="pool"?`將依已儲存份數準備 ${planned} 份獎品，取代目前剩餘 ${totalStock} 份。原有成交與抽獎紀錄會保留。`:"這次調整還沒有儲存。您可以返回編輯，或放棄這次變更。"}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>返回</AlertDialogCancel><AlertDialogAction onClick={()=>{if(confirm==="pool")void pool();else{setConfirm(null);onClose();}}}>{confirm==="pool"?"確認啟用新獎池":"放棄變更並離開"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
