"use client";
import {useEffect,useRef} from "react";
import {Snapshot,wheelSegments,prizeColor} from "@/lib/model";
function point(angle:number,r:number){const a=(angle-90)*Math.PI/180;return [Number((400+r*Math.cos(a)).toFixed(3)),Number((400+r*Math.sin(a)).toFixed(3))];}
function sector(start:number,end:number){if(end-start>=359.999)return "M400 58a342 342 0 1 1 0 684a342 342 0 1 1 0-684";const a=point(start,342),b=point(end,342);return `M400 400L${a[0]} ${a[1]}A342 342 0 ${end-start>180?1:0} 1 ${b[0]} ${b[1]}Z`;}
export default function Wheel({snapshot,rotation=0,spinning=false,ready=false,onSpin,onTick,onFinished,duration=5200}:{snapshot:Snapshot;rotation?:number;spinning?:boolean;ready?:boolean;onSpin?:()=>void;onTick?:()=>void;onFinished?:()=>void;duration?:number}){
 const group=useRef<SVGGElement>(null),last=useRef(0),tick=useRef(onTick),finished=useRef(onFinished);tick.current=onTick;finished.current=onFinished;
 useEffect(()=>{const from=last.current,to=rotation;if(!spinning){group.current?.setAttribute("transform",`rotate(${to} 400 400)`);last.current=to;return;}let frame=0,start:number|undefined,lastNotch=Math.floor(from/9),lastSound=0;const animate=(time:number)=>{start??=time;const t=Math.min((time-start)/duration,1),e=1-Math.pow(1-t,3),a=from+(to-from)*e;group.current?.setAttribute("transform",`rotate(${a} 400 400)`);const notch=Math.floor(a/9);if(notch!==lastNotch&&time-lastSound>42){tick.current?.();lastSound=time;lastNotch=notch;}if(t<1)frame=requestAnimationFrame(animate);else{last.current=to;finished.current?.();}};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame);},[rotation,spinning,duration]);
 const slices=wheelSegments(snapshot);
 return <div className={`wheel-shell ${spinning?"is-spinning":""} ${ready?"is-ready":""}`}><div className="wheel-aura" aria-hidden="true"/><svg className="wheel-svg" viewBox="0 0 800 800" role="img" aria-label={`幸運轉盤：${slices.map(s=>s.prize.shortName).join("、")}`}><defs><linearGradient id="rim" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#7d8085"/><stop offset=".35" stopColor="#363a40"/><stop offset=".7" stopColor="#141414"/><stop offset="1" stopColor="#696e77"/></linearGradient><radialGradient id="hub"><stop stopColor="#252525"/><stop offset="1" stopColor="#111"/></radialGradient><radialGradient id="shine" cx="30%" cy="0%" r="95%"><stop stopColor="#fff" stopOpacity=".14"/><stop offset=".8" stopColor="#fff" stopOpacity="0"/></radialGradient></defs><circle cx="400" cy="400" r="386" fill="#101010" stroke="#3c302a" strokeWidth="1"/><circle cx="400" cy="400" r="372" fill="url(#rim)"/>{Array.from({length:80},(_,i)=>{const a=point(i*4.5,379),b=point(i*4.5,i%5===0?388:384);return <line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke={i%5===0?"#a88a76":"#54483f"} strokeWidth={i%5===0?2:1}/>;})}<circle cx="400" cy="400" r="352" fill="#111" stroke="#ff8a48" strokeOpacity=".45" strokeWidth="1"/><g ref={group}>{slices.map(({prize,start,end,mid})=><g key={prize.id} data-prize-id={prize.id} data-start-angle={start} data-end-angle={end}><path d={sector(start,end)} fill={prizeColor(prize.id)} stroke="#171411" strokeWidth="1.5"/><g transform={`rotate(${mid} 400 400)`}><text x="400" y="180" textAnchor="middle" fill="#172126" fontSize={prize.shortName.length>8?24:28} fontWeight="650" style={{letterSpacing:".02em"}}>{prize.shortName}</text></g></g>)}<circle cx="400" cy="400" r="342" fill="url(#shine)" pointerEvents="none"/></g><circle cx="400" cy="400" r="126" fill="#000" fillOpacity=".22"/><circle cx="400" cy="400" r="113" fill="url(#hub)" stroke="#615043" strokeWidth="1"/><circle cx="400" cy="400" r="103" fill="none" stroke="#36302b" strokeWidth="1"/></svg><div className="wheel-pointer" aria-hidden="true"><span/></div><button className={`wheel-hub ${ready?"can-spin":""}`} onClick={onSpin} disabled={!ready||spinning} aria-label={ready?"開始轉動":"成交後開啟轉盤"}>{spinning?<><span className="hub-kicker">GOOD LUCK</span><strong className="hub-wait">好運<br/>轉動中</strong></>:ready?<><span className="hub-kicker">YOUR MOMENT</span><strong className="hub-start">開始<br/>轉動</strong><span className="hub-touch">TOUCH TO SPIN</span></>:<><strong className="hub-o1">O1<span>®</span></strong><span className="hub-kicker">OMNI PRINTER</span><span className="hub-line"/></>}</button></div>;
}
