import {env} from "cloudflare:workers";
import {ActivitySummary,blankActivityConfig,Config,DEFAULT_CONFIG,Round,StageState,pickOutcome,secureInteger,snapshotOf,taipeiDay,validateConfig} from "./model";

export class StageError extends Error {constructor(public status:number,message:string){super(message);}}
export function db(){if(!env.DB)throw new StageError(503,"活動資料暫時無法連線，請稍後重新整理。");return env.DB;}
const encode=new TextEncoder();
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,"0")).join("");
export const digest=async(value:string)=>hex(await crypto.subtle.digest("SHA-256",encode.encode(value)));
async function pinHash(pin:string,salt:string){const key=await crypto.subtle.importKey("raw",encode.encode(pin),"PBKDF2",false,["deriveBits"]);return hex(await crypto.subtle.deriveBits({name:"PBKDF2",salt:encode.encode(salt),iterations:100000,hash:"SHA-256"},key,256));}
function equal(a:string,b:string){let n=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)n|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return n===0;}
function activityKey(value:unknown){const id=typeof value==="string"&&/^[a-z0-9-]{1,64}$/i.test(value)?value:"main";return id;}
function upgradeConfig(raw:any,id:string):{config:Config;changed:boolean}{const c={...raw} as Config;let changed=false;if(!c.deviceName){c.deviceName=id==="main"?"xTool O1":"xTool 設備";c.activitySchemaVersion=1;changed=true;}if(!c.activitySchemaVersion){c.activitySchemaVersion=1;changed=true;}return {config:c,changed};}
export async function initialize(){
 const d=db();
 const rows=await d.prepare("SELECT id,config,revision,active_round FROM stage_settings").all<{id:string;config:string;revision:number;active_round:string|null}>();
 if(!rows.results.length){const stock=Object.fromEntries(DEFAULT_CONFIG.prizes.map(p=>[p.id,p.quantity]));await d.prepare("INSERT OR IGNORE INTO stage_settings (id,config,stock,revision) VALUES ('main',?,?,0)").bind(JSON.stringify(DEFAULT_CONFIG),JSON.stringify(stock)).run();}
 for(const r of rows.results){const {config,changed}=upgradeConfig(JSON.parse(r.config),r.id);if(changed)await d.prepare("UPDATE stage_settings SET config=?,revision=revision+1 WHERE id=? AND revision=?").bind(JSON.stringify(config),r.id,r.revision).run();}
 const secret=await d.prepare("SELECT salt,hash FROM stage_secrets WHERE id='pin'").first<{salt:string;hash:string}>();
 if(!secret){const salt=crypto.randomUUID(),hash=await pinHash("0000",salt);await d.prepare("INSERT OR IGNORE INTO stage_secrets (id,salt,hash) VALUES ('pin',?,?)").bind(salt,hash).run();}
 else if(equal(await pinHash("1688",secret.salt),secret.hash)){const salt=crypto.randomUUID(),hash=await pinHash("0000",salt);await d.batch([d.prepare("UPDATE stage_secrets SET salt=?,hash=? WHERE id='pin'").bind(salt,hash),d.prepare("DELETE FROM stage_sessions")]);}
}
function cookieValue(request:Request,name:string){return request.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(name+"="))?.slice(name.length+1)||"";}
export async function authorized(request:Request,role="station"){
 const token=cookieValue(request,role==="admin"?"o1_admin":"o1_station");if(!/^[a-f0-9-]{64,80}$/.test(token))return false;
 return !!(await db().prepare("SELECT token_hash FROM stage_sessions WHERE token_hash=? AND role=? AND expires_at>?").bind(await digest(token),role,Date.now()).first());
}
export async function requireAuth(request:Request,role="station"){if(!await authorized(request,role))throw new StageError(401,role==="admin"?"請重新輸入管理 PIN，未儲存的設定仍保留。":"請先輸入工作人員 PIN 啟用此裝置。");}
export function writeGuard(request:Request){const origin=request.headers.get("origin");if((origin&&origin!==new URL(request.url).origin)||request.headers.get("sec-fetch-site")==="cross-site")throw new StageError(403,"不接受其他網站的操作請求。");if(!request.headers.get("content-type")?.includes("application/json"))throw new StageError(415,"請使用正確的資料格式。");}
export async function readBody(request:Request){const body=await request.text();if(body.length>30000)throw new StageError(413,"設定內容過長。");try{return JSON.parse(body);}catch{throw new StageError(400,"無法讀取資料，請再試一次。");}}
async function issueSession(role:string,request:Request){const token=crypto.randomUUID()+crypto.randomUUID(),ttl=role==="admin"?15*60:18*3600;await db().prepare("INSERT INTO stage_sessions (token_hash,role,expires_at) VALUES (?,?,?)").bind(await digest(token),role,Date.now()+ttl*1000).run();return `${role==="admin"?"o1_admin":"o1_station"}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${ttl}${new URL(request.url).protocol==="https:"?"; Secure":""}`;}
export async function login(request:Request,pin:unknown,purpose:unknown){
 if(typeof pin!=="string"||!/^\d{4}$/.test(pin))throw new StageError(400,"請輸入 4 位數 PIN。");
 const d=db(),now=Date.now(),bucket=await digest((request.headers.get("cf-connecting-ip")||"local")+":"+Math.floor(now/300000));
 await d.prepare("INSERT INTO login_attempts (bucket,count,expires_at) VALUES (?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1").bind(bucket,now+300000).run();
 const row=await d.prepare("SELECT count FROM login_attempts WHERE bucket=?").bind(bucket).first<{count:number}>();if((row?.count||0)>6)throw new StageError(429,"嘗試次數較多，請等 5 分鐘後再試。");
 const secret=await d.prepare("SELECT salt,hash FROM stage_secrets WHERE id='pin'").first<{salt:string;hash:string}>();if(!secret||!equal(await pinHash(pin,secret.salt),secret.hash))throw new StageError(401,"PIN 不正確，請再試一次。");
 await d.batch([d.prepare("DELETE FROM login_attempts WHERE bucket=? OR expires_at<?").bind(bucket,now),d.prepare("DELETE FROM stage_sessions WHERE expires_at<?").bind(now)]);
 const cookies=[await issueSession("station",request)];if(purpose==="admin")cookies.push(await issueSession("admin",request));return cookies;
}
export async function logout(request:Request){const tokens=[cookieValue(request,"o1_station"),cookieValue(request,"o1_admin")];await db().batch(await Promise.all(tokens.map(async t=>db().prepare("DELETE FROM stage_sessions WHERE token_hash=?").bind(await digest(t)))));return ["o1_station=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0","o1_admin=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0"];}
export async function changePin(request:Request,body:any){await requireAuth(request,"admin");if(typeof body.newPin!=="string"||!/^\d{4}$/.test(body.newPin)||body.newPin!==body.confirmPin)throw new StageError(400,"新 PIN 必須為 4 位數，且兩次輸入相同。");const old=await db().prepare("SELECT salt,hash FROM stage_secrets WHERE id='pin'").first<{salt:string;hash:string}>();if(!old||typeof body.currentPin!=="string"||!equal(await pinHash(body.currentPin,old.salt),old.hash))throw new StageError(400,"目前 PIN 不正確。");const salt=crypto.randomUUID(),hash=await pinHash(body.newPin,salt),station=await digest(cookieValue(request,"o1_station")),admin=await digest(cookieValue(request,"o1_admin"));await db().batch([db().prepare("UPDATE stage_secrets SET salt=?,hash=? WHERE id='pin'").bind(salt,hash),db().prepare("DELETE FROM stage_sessions WHERE token_hash NOT IN (?,?)").bind(station,admin)]);}
type SettingsRow={config:string;stock:string;revision:number;active_round:string|null;operation:string|null};
export async function settingsRow(activityId="main"){const id=activityKey(activityId),r=await db().prepare("SELECT config,stock,revision,active_round,operation FROM stage_settings WHERE id=?").bind(id).first<SettingsRow>();if(!r)throw new StageError(404,"找不到這個活動，請回到活動選單重新選擇。");return r;}
function roundFrom(r:any):Round{return {id:r.id,sequence:r.sequence,createdAt:r.created_at,drawnAt:r.drawn_at,completedAt:r.completed_at,status:r.status,snapshot:JSON.parse(r.snapshot),outcome:r.outcome?JSON.parse(r.outcome):null,note:r.note,day:r.day};}
export async function getRound(id:string){const r=await db().prepare("SELECT * FROM rounds WHERE id=?").bind(id).first();return r?roundFrom(r):null;}
function belongs(round:Round,activityId:string){return round.snapshot.activityId===activityId||(activityId==="main"&&!round.snapshot.activityId);}
function roundScope(activityId:string){return activityId==="main"?"(json_extract(snapshot,'$.activityId')='main' OR json_extract(snapshot,'$.activityId') IS NULL)":"json_extract(snapshot,'$.activityId')=?";}
export async function listActivities(request:Request){const rows=await db().prepare("SELECT id,config,revision,active_round FROM stage_settings ORDER BY CASE WHEN id='main' THEN 0 ELSE 1 END,rowid").all<any>();const activities:ActivitySummary[]=rows.results.map(r=>{const c:Config=upgradeConfig(JSON.parse(r.config),r.id).config;return {id:r.id,deviceName:c.deviceName,eventName:c.eventName,mode:c.mode,prizeCount:c.prizes.length,active:!!r.active_round,revision:r.revision};});return {activities,authenticated:await authorized(request,"admin")};}
export async function createActivity(request:Request,body:any){await requireAuth(request,"admin");const deviceName=typeof body.deviceName==="string"?body.deviceName.trim():"",eventName=typeof body.eventName==="string"?body.eventName.trim():"";if(!deviceName||deviceName.length>30||!eventName||eventName.length>60)throw new StageError(400,"請填寫設備名稱與活動名稱。");let config:Config;if(body.sourceActivityId){const source=await settingsRow(activityKey(body.sourceActivityId));config=structuredClone(upgradeConfig(JSON.parse(source.config),activityKey(body.sourceActivityId)).config);config.deviceName=deviceName;config.eventName=eventName;config.announcement=`恭喜現場貴賓完成 ${deviceName} 下訂`;config.poolNumber=1;}else config=blankActivityConfig(deviceName,eventName);config=validateConfig(config);const id=crypto.randomUUID(),stock=Object.fromEntries(config.prizes.map(p=>[p.id,config.mode==="pool"?p.quantity:0]));await db().prepare("INSERT INTO stage_settings (id,config,stock,revision,active_round,operation) VALUES (?,?,?,0,NULL,NULL)").bind(id,JSON.stringify(config),JSON.stringify(stock)).run();return {id,deviceName,eventName,mode:config.mode,prizeCount:config.prizes.length,active:false,revision:0} satisfies ActivitySummary;}
export async function readState(request:Request,activityId="main"):Promise<StageState>{
 const id=activityKey(activityId),d=db(),row=await settingsRow(id),day=taipeiDay(),scope=roundScope(id);
 const countSql=`SELECT COUNT(*) AS started,COALESCE(SUM(CASE WHEN drawn_at IS NOT NULL THEN 1 ELSE 0 END),0) AS completed FROM rounds WHERE day=? AND ${scope}`;
 const prizeSql=`SELECT json_extract(outcome,'$.prize.id') AS prize,COUNT(*) AS n FROM rounds WHERE day=? AND drawn_at IS NOT NULL AND ${scope} GROUP BY json_extract(outcome,'$.prize.id')`;
 const countQ=id==="main"?d.prepare(countSql).bind(day):d.prepare(countSql).bind(day,id),prizeQ=id==="main"?d.prepare(prizeSql).bind(day):d.prepare(prizeSql).bind(day,id);
 const [active,auth,counts,prizeCounts]=await Promise.all([row.active_round?getRound(row.active_round):null,authorized(request),countQ.first<{started:number;completed:number}>(),prizeQ.all<{prize:string;n:number}>()]);
 const config:Config=upgradeConfig(JSON.parse(row.config),id).config;if(!auth){config.prizes=config.prizes.map(p=>({...p,cost:null}));if(active){active.note="";active.snapshot.prizes=active.snapshot.prizes.map(p=>({...p,cost:null}));if(active.outcome)active.outcome.prize={...active.outcome.prize,cost:null};}}
 return {activityId:id,config,stock:JSON.parse(row.stock),active,authenticated:auth,stats:{started:counts?.started||0,completed:counts?.completed||0,byPrize:Object.fromEntries(prizeCounts.results.map(r=>[r.prize,r.n]))},revision:row.revision,serverNow:Date.now()};
}
export async function startRound(request:Request,idValue:unknown,activityId="main"){
 await requireAuth(request);const activity=activityKey(activityId);if(typeof idValue!=="string"||!/^[a-f0-9-]{36}$/.test(idValue))throw new StageError(400,"成交識別碼不正確，請重新整理。");
 const d=db(),row=await settingsRow(activity),existing=await getRound(idValue);if(existing){if(!belongs(existing,activity))throw new StageError(409,"成交識別碼屬於其他活動。");return existing;}if(row.active_round)throw new StageError(409,"這個活動已有一筆成交正在抽獎，請先完成。");
 const config:Config=JSON.parse(row.config),snapshot=snapshotOf(config,JSON.parse(row.stock),activity);if(snapshot.total<=0)throw new StageError(409,"本場獎池已抽完，請工作人員補充獎池後再確認成交。");const now=Date.now();
 await d.batch([d.prepare("INSERT OR IGNORE INTO rounds (id,sequence,created_at,day,status,snapshot,note) SELECT ?,COALESCE((SELECT MAX(sequence) FROM rounds),0)+1,?,?,'confirmed',?,'' FROM stage_settings WHERE id=? AND active_round IS NULL AND revision=?").bind(idValue,now,taipeiDay(now),JSON.stringify(snapshot),activity,row.revision),d.prepare("UPDATE stage_settings SET active_round=?,revision=revision+1 WHERE id=? AND active_round IS NULL AND revision=? AND EXISTS (SELECT 1 FROM rounds WHERE id=? AND status='confirmed')").bind(idValue,activity,row.revision,idValue)]);
 const after=await settingsRow(activity);if(after.active_round&&after.active_round!==idValue)throw new StageError(409,"這個活動已有一筆成交正在抽獎，請先完成。");const round=await getRound(idValue);if(!round)throw new StageError(409,"活動設定剛剛更新，請再按一次確認成交。");return round;
}
export async function drawRound(request:Request,idValue:unknown,activityId="main"){
 await requireAuth(request);const activity=activityKey(activityId);if(typeof idValue!=="string")throw new StageError(400,"請先確認成交。");const d=db(),row=await settingsRow(activity),round=await getRound(idValue);if(!round||!belongs(round,activity))throw new StageError(404,"找不到這筆成交，請重新整理。");if(round.outcome)return round;if(row.active_round!==idValue)throw new StageError(409,"這筆成交並非目前抽獎。");
 const outcome=pickOutcome(round.snapshot,secureInteger(round.snapshot.total)),stock:Record<string,number>=JSON.parse(row.stock),nonce=crypto.randomUUID();if(round.snapshot.mode==="pool"){if(!(stock[outcome.prize.id]>0))throw new StageError(409,"獎池數量已變動，請聯絡工作人員。");stock[outcome.prize.id]--;}
 await d.batch([d.prepare("UPDATE rounds SET status='drawn',drawn_at=?,outcome=?,draw_nonce=? WHERE id=? AND status='confirmed' AND EXISTS (SELECT 1 FROM stage_settings WHERE id=? AND active_round=? AND revision=?)").bind(Date.now(),JSON.stringify(outcome),nonce,idValue,activity,idValue,row.revision),d.prepare("UPDATE stage_settings SET stock=?,revision=revision+1 WHERE id=? AND active_round=? AND revision=? AND EXISTS (SELECT 1 FROM rounds WHERE id=? AND draw_nonce=?)").bind(JSON.stringify(stock),activity,idValue,row.revision,idValue,nonce)]);
 const result=await getRound(idValue);if(!result?.outcome)throw new StageError(409,"畫面資料剛剛更新，請再按一次開始轉動。");return result;
}
export async function completeRound(request:Request,idValue:unknown,note:unknown,activityId="main"){
 await requireAuth(request);const activity=activityKey(activityId);if(typeof idValue!=="string"||typeof note!=="string"||note.length>160)throw new StageError(400,"備註限 160 字以內。");const round=await getRound(idValue);if(!round?.outcome||!belongs(round,activity))throw new StageError(409,"請先完成抽獎。");if(round.status==="complete")return;const d=db();await d.batch([d.prepare("UPDATE rounds SET status='complete',completed_at=?,note=? WHERE id=? AND status='drawn' AND EXISTS (SELECT 1 FROM stage_settings WHERE id=? AND active_round=?)").bind(Date.now(),note.trim(),idValue,activity,idValue),d.prepare("UPDATE stage_settings SET active_round=NULL,revision=revision+1 WHERE id=? AND active_round=? AND EXISTS (SELECT 1 FROM rounds WHERE id=? AND status='complete')").bind(activity,idValue,idValue)]);
}
export async function saveSettings(request:Request,body:any,activityId="main"){await requireAuth(request,"admin");const activity=activityKey(activityId),row=await settingsRow(activity);if(row.active_round)throw new StageError(409,"請先完成目前抽獎，再修改活動設定。");let config:Config;try{config=validateConfig(body.config);}catch(e){throw new StageError(400,(e as Error).message);}const saved:Config=JSON.parse(row.config);config.poolNumber=saved.poolNumber;const result=await db().prepare("UPDATE stage_settings SET config=?,revision=revision+1 WHERE id=? AND active_round IS NULL AND revision=?").bind(JSON.stringify(config),activity,body.revision).run();if(!result.meta.changes)throw new StageError(409,"其他裝置已更新設定，請關閉後重新開啟管理設定。");}
export async function resetPool(request:Request,revision:unknown,activityId="main"){await requireAuth(request,"admin");const activity=activityKey(activityId),row=await settingsRow(activity);if(row.active_round)throw new StageError(409,"請先完成目前抽獎。");const config:Config=JSON.parse(row.config);if(!config.prizes.some(p=>p.quantity>0))throw new StageError(400,"請先設定至少一份獎品並儲存。");config.poolNumber++;const stock=Object.fromEntries(config.prizes.map(p=>[p.id,p.quantity]));const r=await db().prepare("UPDATE stage_settings SET config=?,stock=?,revision=revision+1 WHERE id=? AND active_round IS NULL AND revision=?").bind(JSON.stringify(config),JSON.stringify(stock),activity,revision).run();if(!r.meta.changes)throw new StageError(409,"資料已更新，請重新開啟管理設定。");}
export async function history(request:Request,day:string|null,activityId="main"){await requireAuth(request,"admin");const activity=activityKey(activityId);if(day&&!/^\d{4}-\d{2}-\d{2}$/.test(day))throw new StageError(400,"日期格式不正確。");const scope=roundScope(activity),sql=`SELECT * FROM rounds WHERE ${day?"day=? AND ":""}${scope} ORDER BY sequence DESC LIMIT 100`;const q=activity==="main"?(day?db().prepare(sql).bind(day):db().prepare(sql)):(day?db().prepare(sql).bind(day,activity):db().prepare(sql).bind(activity));return (await q.all()).results.map(roundFrom);}
